name: Continuous integration
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install frontend requirements
      run: npm ci
      working-directory: ./Application
    - name: Lint frontend
      run: npm run lint
      working-directory: ./Application
    - name: Build frontend
      run: npm run build
      working-directory: ./Application

  release:
    if: github.ref == 'refs/heads/master'
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: deploy dist
      uses: appleboy/gh-pages-action@v0.0.2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        target_branch: master
        pages_directory: dist
        remote_url: https://github.com/ManuelWe/ManuelWe.github.io.git
