name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install frontend requirements
      run: npm ci
      working-directory: ./Application
    - name: Lint frontend
      run: npm run lint
      working-directory: ./Application
    - name: Build frontend
      run: npm run build
      working-directory: ./Application
    - name: deploy dist
      uses: JamesIves/github-pages-deploy-action@3.4.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: Application/dist
        REPOSITORY_NAME: ManuelWe/ManuelWe.github.io
        DEBUG: true
