name: Code Validation
on:
  pull_request:
    branches:
      - master
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install frontend requirements
      run: npm ci
      working-directory: ./Application
    - name: Lint frontend
      run: npm run lint
      working-directory: ./Application
    - name: Build frontend
      run: npm run build
      working-directory: ./Application
